# Generated by Django 6.0.1 on 2026-02-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeadSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_type', models.CharField(choices=[('corporate', 'Корпоративні послуги'), ('infidelity', 'Перевірка на зраду'), ('cta', 'CTA заявка'), ('consultation', 'Консультація')], db_index=True, help_text='Тип форми, з якої надійшла заявка', max_length=20)),
                ('status', models.CharField(choices=[('new', 'Нова'), ('contacted', "Зв'язалися"), ('in_progress', 'В роботі'), ('completed', 'Завершено'), ('cancelled', 'Скасовано')], db_index=True, default='new', help_text='Статус обробки заявки', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Дата та час отримання заявки')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата та час останньої зміни')),
                ('name', models.CharField(db_index=True, help_text="Ім'я клієнта", max_length=100)),
                ('phone', models.CharField(blank=True, db_index=True, help_text='Номер телефону', max_length=20)),
                ('email', models.EmailField(blank=True, db_index=True, help_text='Email адреса', max_length=254)),
                ('message', models.TextField(blank=True, help_text='Повідомлення або коментар')),
                ('contact', models.CharField(blank=True, help_text='Контакт (Telegram або телефон) для консультації', max_length=100)),
                ('telegram_sent', models.BooleanField(db_index=True, default=False, help_text='Чи була заявка відправлена в Telegram')),
                ('telegram_sent_at', models.DateTimeField(blank=True, help_text='Дата та час відправки в Telegram', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP адреса клієнта', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User-Agent браузера')),
                ('admin_notes', models.TextField(blank=True, help_text='Внутрішні нотатки адміністратора')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='pages_leads_created_f15cbd_idx'), models.Index(fields=['form_type', '-created_at'], name='pages_leads_form_ty_3426f3_idx'), models.Index(fields=['status', '-created_at'], name='pages_leads_status_8b3ddb_idx')],
            },
        ),
    ]
